@startuml

[*] --> Init
Init : initialize parameters
Stop: stopp controller
Op : control_velocity(v = target_velocity)

Init : set_led(led = off)
Stop: set_led(led = 2Hz) 
Op : set_led(led = on)

Init --> Op
Init --> Stop : stop()

Op --> Init : reset()
Op --> Stop : stop()

Stop --> Op : set_op()
Stop --> Init : reset()

@enduml
