@startuml

[*] --> Init
Init : initialize parameters
Stop: stopp controller
PreOp : waiting for command
Op : control_velocity(v = target_velocity)

Init : set_led(led = off)
Stop: set_led(led = 2Hz) 
PreOp : set_led(led = 1Hz) 
Op : set_led(led = on)

PreOp : send_boot_up_message()

PreOp : set_kp(Kp)
PreOp : set_ti(Ti)

Init --> PreOp
Init --> Stop : emergency_stop()
PreOp --> Op : set_op()
PreOp --> Stop : stop() \n emergency_stop()
PreOp --> Init : reset()

Op --> Init : reset()
Op --> Stop : stop() \n emergency_stop()
Op --> PreOp : set_pre()

Stop --> Op : set_op()
Stop --> PreOp : set_pre()
Stop --> Init : reset()

@enduml
