@startuml

[*] --> Init
Init : initialize parameters
Stop: stopp controller
PreOp : waiting for command
Op : control_velocity(v = target_velocity)

Init : set_led(led = off)
Stop: set_led(led = 2Hz) 
PreOp : set_led(led = 1Hz) 
Op : set_led(led = on)

PreOp : send_boot_up_message()

PreOp : set_kp(kp)
PreOp : set_ti(ti)
PreOp : set_type(controller_allgorithm)

Init --> PreOp
Init --> Stop : stop()
PreOp --> Op : set_op()
PreOp --> Stop : stop()
PreOp --> Init : reset()

Op --> Init : reset()
Op --> Stop : stop()
Op --> PreOp : set_preop()

Stop --> Op : set_op()
Stop --> PreOp : set_preop()
Stop --> Init : reset()

@enduml
